# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Try
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Gathering deps
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3-pip
          sudo pip3 install pytest
      - name: Install
        env:
          NAME: Hamada
        run: |
          echo "::set-env name=name::$NAME"
          sudo pytest testcase.py -sv
