# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Try
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Gathering deps
        run: |
          sudo apt-get update
          sudo apt-get install -y git python3-pip python3-venv python3-setuptools tmux redis
          sudo pip3 install poetry
      - name: Install
        run: |
          git clone https://github.com/threefoldtech/js-sdk.git
          cd js-sdk
          sudo poetry run pip3 install pytest
          sudo poetry update
          sudo poetry install
      - name: Run tests
        env: 
          TNAME: ${{ secrets.TNAME }}
          EMAIL: ${{ secrets.EMAIL }}
          WORDS: ${{ secrets.WORDS }}
          WALLET_NAME: ${{ secrets.WALLET_NAME }}
          WALLET_SECRET: ${{ secrets.WALLET_SECRET }}
        run: |
          cd js-sdk
          sudo poetry run jsng "j.core.identity.get('default', tname='$TNAME', email='$EMAIL', words='$WORDS', explorer_url='https://explorer.testnet.grid.tf/api/v1')"
          sudo poetry run pytest ../payment -s 

